she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('author/<str:username>', views.AuthorView.as_view(), name='profile'),
    path('edit/<int:pk>', views.UpdateStoryView.as_view(), name='update'),
    # path('<int:pk>/delete', views.DeleteStoryView.as_view(), name='delete'),

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns =[
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    # path('update/', include('update.urls')),
    # path('delete/', include('delete.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView

app_name = 'users'
urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), 
    name='createAccount')
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    category = models.CharField(max_length=255, default='uncategorized')
    content = models.TextField()
    preview = models.CharField(max_length=300)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser
class CustomUser(AbstractUser):
   pass

   def __str__(self):
        return self.username

she_codes_news/news/forms.py
# news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, Category
from django.core.validators import EmailValidator

choices = Category.objects.all().values_list('name','name')

choice_list = []

for item in choices:
    choice_list.append(item)


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory 
        fields = ['title', 'pub_date', 'content', 'preview', 'category', 'image']
        widgets = {          
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'preview': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Write your preview: this will appear below your title" }),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'pub_date': forms.DateTimeInput(
                format='%m/%d/%Y %H:%M',
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'datetime-local'
                }
            )
        }

# class ContactForm(forms.form):
#     name = forms.CharField(required=True)
#     email = forms.EmailField(validators=[EmailValidator()})
#     message = forms.CharField(widget=forms.Textarea)

she_codes_news/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from typing import Any
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm
from users.models import CustomUser
from django.shortcuts import get_object_or_404
# from django.shortcuts import render, redirect
# from .forms import ContactForm
# from django.http import HttpResponse

class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class AuthorView(generic.DetailView):
    model = CustomUser
    template_name = 'news/author.html'
    context_object_name = 'author'

    def get_object(self, *args, **kwargs):
        return get_object_or_404 (CustomUser, username=self.kwargs['username'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.filter(author_id=self.object.id)
        return context
    

class UpdateStoryView(generic.UpdateView):
    model = NewsStory
    template_name = 'news/editStory.html'
    fields = ('title', 'image_url', 'content')
    success_url = reverse_lazy('news:index')


# class DeleteStoryView(generic.DeleteView):
#     model = NewsStory
#     template_name = 'news/delete.html'
#     success_url = reverse_lazy('news:index')

# def contact(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             # Process the form data
#             pass
#             return redirect('success')
#     else:
#         form = ContactForm()
#     return render(request, 'contact.html', {'form': form})


# def success(request):
#    return HttpResponse('Success!')

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic

from .models import CustomUser
from .forms import CustomUserCreationForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

she_codes_news/news/templates/news/author.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}

{% block content %}
<br>
<a href="{% url 'news:newStory' %}">Write New Story</a>

<h2>Stories by {{ author.username }}</h2>

<div id="latest-stories">
    {% if author.newsstory_set %}
    {% for story in author.newsstory_set.all %}
    {% include "./storyCard.html" with story=story position=forloop.counter %}
    {% endfor %}
    {% else %}
    <p>No stories are available.</p>
    {% endif %}
</div>

<div id="all-stories">
    {% if latest_stories %}
    {% for story in all_stories %}
    {% include "./storyCard.html" with story=story %}
    {% endfor %}
    {% else %}
    <p>No stories are available.</p>
    {% endif %}
</div>
{% endblock %}

she_codes_news/news/templates/news/contact.html
<form action="/contact/" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    <input type="submit" value="Submit">
</form>

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
</form>

{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}

{% block content %}
    <br>
    {% if request.user.is_authenticated %}
    <a href="{% url 'news:newStory' %}">Write New Story</a>
    {% endif %}


<h2>Latest News</h2>
    
    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}

    </div>
{% endblock %}

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}
{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        <img src="image/">
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image %}
            <img src="{{story.images.url}}">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
            <br/>
            <p>{{ story.preview }}</p>
        </div>
    </a>
</div>

she_codes_news/news/templates/news/update.html
<!-- {% extends "base.html" %}
{% block title %}Edit Story{% endblock %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %} -->

she_codes_news/templates/base.html
{% load static %}

    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Farran">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %} {% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>
        {% block content %}{% endblock %}
    </body>

she_codes_news/templates/nav.html
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a href="#">{{ user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
{% endif %}

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
    <h2>Create Account</h2>
    <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create Account</button>
    </form>
{% endblock %}